spring.config.activate.on-profile: docker
server.port: 8080
spring.cloud.stream.kafka.binder.brokers: broker
spring.data.mongodb.host: mongodb
#spring.rabbitmq.host: rabbitmq

app.eureka-server: eureka